services:
  postgres:
    image: postgres:16
    container_name: movie_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ibeathadesthismorning
      POSTGRES_DB: movie_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
